apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 617371012467.dkr.ecr.us-east-1.amazonaws.com/manu-orders:latest
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              value: "4002"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: manu-secrets
                  key: JWT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: manu-secrets
                  key: MONGO_URI_ORDERS
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 4002
      targetPort: 4002
